
%macro doublesort_indep_control(dataname,tvar,varnme,wvar,varc,vars,numc,nums,outname);
ods noresults;
ods exclude all;
ods graphics off;
*;
proc sort data=&dataname;by &tvar &varc;run;
proc rank data=&dataname out=rankc  group=&numc;
  by &tvar;
  var &varc;
  ranks rankc;
run;
proc sort data=rankc;by &tvar &vars;run;
proc rank data=rankc out=ranks group=&nums;by &tvar;
var &vars; ranks ranks;
run;
proc sort data=ranks;by &tvar rankc ranks;run;
data ranks;set ranks;
rankc=rankc+1;ranks=ranks+1;
run;
*Summarize the bond numbers in each rank in each month;
*calculate the means;
%if %length(&wvar)~=0 %then %do;
	proc means data=ranks noprint;
		by &tvar rankc ranks;
		var &varnme;
		weight &wvar;
		output out=_mean_1 mean=/autoname noinherit;
	run;
%end;
%if %length(&wvar)=0 %then %do;
	proc means data=ranks noprint;
		by &tvar rankc ranks;
		var &varnme;
		output out=_mean_1 mean=/autoname noinherit;
	run;
%end;

data &outname;set _mean_1;
	do i=1 to &numc;
		do j=1 to &nums;
			if rankc=i and ranks=j then portname=compress(cat("port",put(i,2.),put(j,2.)));
		end;
	end;
	format portname $8.;
	drop i j _type_;
run;
*;
proc datasets library=work nolist noprint;
	delete _mean_l _t_mean_1 ranks rankc;
quit;
*;
ods graphics on;
ods exclude none;
ods results;
%mend doublesort_indep_control;
